# Generated by Django 5.2.6 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_winner_alter_game_active_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active_player',
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.CharField(choices=[('X', 'Player X'), ('O', 'Player O')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('X', 'Player X'), ('O', 'Player O')], max_length=1, null=True),
        ),
    ]
