# Generated by Django 5.2.6 on 2025-11-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_is_active_game_is_draw_game_player_o_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_draw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_o',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_x',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
